{application, iris,
 [{description, "Scalable xmpp bot"},
  {vsn, "0.1.0"},
  {registered, [root, main_sup]},
  {modules, [iris, 
	     core,
	     jid_worker,
	     config,
	     ulog,
	     muc_tools,
	     foo,
	     erronious_module,
	     default_module,
	     exit,
	     g,
	     tw,
	     external_interface,
	     word,
	     iris_module,
	     gelb,
	     qw
	    ]},
  {mod, {iris,[]}},
  {applications, [kernel]},
  {env, []}
]}.
